# Generated by Django 6.1 on 2026-09-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='custom_fields_schema',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
