# Generated by Django 6.1 on 2026-08-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('order_status', 'Order Status'), ('document_ready', 'Document Ready'), ('reminder', 'Reminder'), ('approval_required', 'Approval Required'), ('payment_received', 'Payment Received'), ('assigned_to_lab', 'Assigned To Lab'), ('receipt_uploaded', 'Receipt Uploaded')], max_length=20, null=True),
        ),
    ]
