"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-au688@s@z3pg01@unpo0zamn+($-%bky)1ijk-m(&*n(x1@pqc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


JWT_SECRET = os.environ.get("JWT_SECRET")
JWT_EXPIRATION_MS = int(os.environ.get("JWT_EXPIRATION_MS", 86400000))


EXECUTOR_NAME = os.environ.get("EXECUTOR_NAME", "ТОО Метрологическая служба")
EXECUTOR_BIN = os.environ.get("EXECUTOR_BIN", "")
EXECUTOR_ADDRESS = os.environ.get("EXECUTOR_ADDRESS", "")
EXECUTOR_PHONE = os.environ.get("EXECUTOR_PHONE", "")
EXECUTOR_BANK = os.environ.get("EXECUTOR_BANK", "")


# Потолок тела запроса. Вложения уходят в JSON base64-строкой, то есть в 4/3
# раза длиннее файла, и в одном запросе их бывает два (доверенность +
# документация при подаче заявки; два черновика экспертизы). Отсюда минимум:
# 2 x 7 МиБ x 4/3 = 18.7 МиБ, плюс обвязка. Двигать это число можно только
# вместе с MAX_ATTACHMENT_MB в orders/views.py — иначе лимит на документ
# снова станет недостижимым.
DATA_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "users.authentication.JwtAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_RENDERER_CLASSES": (
        "djangorestframework_camel_case.render.CamelCaseJSONRenderer",
    ),
    "DEFAULT_PARSER_CLASSES": (
        "djangorestframework_camel_case.parser.CamelCaseJSONParser",
    ),
}

# custom_fields_values хранит значения по ключам из Service.custom_fields_schema
# (field.key - снейк-кейс, задаётся менеджером через шаблон услуги). Без
# ignore_fields камелайзер рекурсивно переименовал бы и эти вложенные ключи
# при отдаче через API (manufacturer_name -> manufacturerName), а схема
# по-прежнему возвращала бы key как есть (это строковое значение, а не ключ
# словаря) - фронт не смог бы сопоставить values[field.key] и увидел бы поля
# пустыми при повторном открытии заявки.
JSON_CAMEL_CASE = {
    "JSON_UNDERSCOREIZE": {
        "ignore_fields": ("custom_fields_values",),
    },
}


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'corsheaders',

    'rest_framework',

    'users',
    'companies',
    'laboratories',
    'catalog',
    'orders',
    'notifications',
    'devices',
    'msgs',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    # Ниже CorsMiddleware намеренно: иначе на ответ 413 не навесятся
    # CORS-заголовки и браузер покажет сетевую ошибку вместо статуса.
    'config.middleware.RequestTooBigJsonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
]

# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DB_NAME"),
        "USER": os.environ.get("DB_USER"),
        "PASSWORD": os.environ.get("DB_PASSWORD"),
        "HOST": os.environ.get("DB_HOST"),
        "PORT": os.environ.get("DB_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Default primary key field type
# https://docs.djangoproject.com/en/6.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'