# Generated by Django 6.1 on 2026-08-17 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('laboratories', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending_contract', 'Pending Contract'), ('awaiting_approval', 'Awaiting Approval'), ('awaiting_director', 'Awaiting Director'), ('awaiting_payment', 'Awaiting Payment'), ('awaiting_delivery', 'Awaiting Delivery'), ('received_in_lab', 'Received In Lab'), ('in_work', 'In Work'), ('under_review', 'Under Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('annulled', 'Annulled'), ('terminated', 'Terminated')], default='pending_contract', max_length=30)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('payment_comment', models.TextField(blank=True, null=True)),
                ('client_comment', models.TextField(blank=True, null=True)),
                ('invoice_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_client', to='users.user')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratories.laboratory')),
                ('metrologist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_as_metrologist', to='users.user')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.service')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=255, unique=True)),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('signed', 'Signed'), ('rejected', 'Rejected'), ('annulled', 'Annulled'), ('terminated', 'Terminated')], default='draft', max_length=20)),
                ('client_signed', models.BooleanField(default=False)),
                ('client_signed_at', models.DateTimeField(blank=True, null=True)),
                ('director_signed', models.BooleanField(default=False)),
                ('director_signed_at', models.DateTimeField(blank=True, null=True)),
                ('annulled_at', models.DateTimeField(blank=True, null=True)),
                ('annulled_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('terminated_at', models.DateTimeField(blank=True, null=True)),
                ('terminated_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('annulled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_annulled', to='users.user')),
                ('client_signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_signed_as_client', to='users.user')),
                ('director_signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_signed_as_director', to='users.user')),
                ('terminated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_terminated', to='users.user')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'db_table': 'contracts',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(max_length=255)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('serial_number', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.CharField(blank=True, choices=[('certificate', 'Certificate'), ('protocol', 'Protocol'), ('report', 'Report')], max_length=20, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('is_signed', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('metrologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_as_metrologist', to='users.user')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'db_table': 'results',
            },
        ),
    ]
