# Generated by Django 6.1 on 2026-08-31 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_invoice_amount_order_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expertise_conclusion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='power_of_attorney_file',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='power_of_attorney_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tech_documentation_file',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tech_documentation_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='test_program_draft_file',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='test_program_draft_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='type_description_draft_file',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='type_description_draft_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='manufacturer_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='manufacturer_country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='manufacturer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='metrological_characteristics',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_contract', 'Pending Contract'), ('revision', 'Revision'), ('awaiting_approval', 'Awaiting Approval'), ('awaiting_director', 'Awaiting Director'), ('awaiting_payment', 'Awaiting Payment'), ('pending_delivery', 'Pending Delivery'), ('awaiting_delivery', 'Awaiting Delivery'), ('received_in_lab', 'Received In Lab'), ('expertise', 'Expertise'), ('in_work', 'In Work'), ('under_review', 'Under Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('annulled', 'Annulled'), ('terminated', 'Terminated')], default='pending_contract', max_length=30),
        ),
    ]
