# Generated by Django 6.1 on 2026-09-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_contract', 'Pending Contract'), ('revision', 'Revision'), ('awaiting_approval', 'Awaiting Approval'), ('awaiting_payment', 'Awaiting Payment'), ('pending_delivery', 'Pending Delivery'), ('awaiting_delivery', 'Awaiting Delivery'), ('received_in_lab', 'Received In Lab'), ('expertise', 'Expertise'), ('in_work', 'In Work'), ('under_review', 'Under Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('annulled', 'Annulled'), ('terminated', 'Terminated')], default='pending_contract', max_length=30),
        ),
    ]
