from django.urls import path
from . import views

urlpatterns = [
    path("results/", views.create_result, name="create-result"),
    path("orders/", views.orders_list, name="orders-list-create"),
    path("orders/my-orders/", views.get_my_orders, name="my-orders"),
    path("orders/lab/<int:lab_id>/", views.get_orders_by_lab_id, name="orders-by-lab"),
    path("orders/status/<str:status>/", views.get_orders_by_status, name="orders-by-status"),
    path("orders/<int:id>/", views.order_detail, name="order-detail"),
    path("orders/<int:id>/items/", views.get_order_items, name="order-items"),
    path("orders/<int:id>/status/", views.update_order_status, name="order-update-status"),
    path("orders/<int:id>/return/", views.return_to_revision, name="order-return"),
    path("orders/<int:id>/resubmit/", views.resubmit_order, name="order-resubmit"),
    path("orders/<int:id>/send-invoice/", views.send_invoice, name="order-send-invoice"),
    path("orders/<int:id>/upload-receipt/", views.upload_receipt, name="order-upload-receipt"),
    path("orders/<int:id>/receipt/", views.get_receipt, name="order-get-receipt"),
    path("orders/<int:id>/set-price/", views.set_price, name="order-set-price"),
    path("orders/<int:id>/payment/", views.confirm_payment, name="order-confirm-payment"),
    path("orders/<int:id>/notify-director/", views.notify_director, name="order-notify-director"),
    path("orders/<int:id>/assign-lab/", views.assign_to_lab, name="order-assign-lab"),
    path("orders/<int:id>/submit-expertise/", views.submit_expertise, name="order-submit-expertise"),
    path("contracts/<int:order_id>/", views.contract_detail, name="contract-detail"),
    path("contracts/<int:order_id>/file/", views.download_contract_file, name="contract-file"),
    path("contracts/<int:order_id>/submit/", views.resubmit_for_approval, name="contract-submit"),
    path("contracts/<int:order_id>/approve/", views.approve_contract, name="contract-approve"),
    path("contracts/<int:order_id>/reject/", views.reject_contract, name="contract-reject"),
    path("contracts/<int:order_id>/sign/approver/", views.sign_by_approver, name="contract-sign-approver"),
    path("contracts/<int:order_id>/sign/financier/", views.sign_by_financier, name="contract-sign-financier"),
    path("contracts/<int:order_id>/sign/director/", views.sign_by_director, name="contract-sign-director"),
    path("contracts/<int:order_id>/sign/client/", views.sign_by_client, name="contract-sign-client"),
    path("contracts/<int:order_id>/sign/gen_director/", views.sign_by_gen_director, name="contract-sign-gen-director"),
    path("contracts/<int:order_id>/annul/", views.annul_contract, name="contract-annul"),
    path("contracts/<int:order_id>/terminate/", views.terminate_contract, name="contract-terminate"),
    path("contracts/<int:order_id>/download/", views.download_contract, name="contract-download"),
    path("pdf/certificate/<int:order_id>/", views.download_certificate, name="certificate-download"),
    path("pdf/invoice/<int:order_id>/", views.download_invoice, name="invoice-download"),
    path("results/order/<int:order_id>/", views.get_results_by_order, name="results-by-order"),
    path("stats/", views.get_stats, name="stats"),
]