# Generated by Django 6.1 on 2026-08-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=12, unique=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('client', 'Client'), ('metrolog', 'Metrolog'), ('manager', 'Manager'), ('director', 'Director'), ('gen_director', 'General Director'), ('financier', 'Financier'), ('approver', 'Approver'), ('admin', 'Admin')], max_length=20)),
                ('company_id', models.IntegerField(blank=True, null=True)),
                ('lab_id', models.IntegerField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('password_reset_token', models.CharField(blank=True, max_length=255, null=True)),
                ('password_reset_expires', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
